# Generated by Django 2.1.1 on 2018-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogengine', '0003_auto_20180904_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
